### ISSUE TITLE
Not getting any accesories configured 

### ISSUE THREAD

**Issue by steveternes** [tonesto7/homebridge-smartthings#209]
Able to add the homebridge but no accessories are showing up, have them configured in the app.  Am I supposed to add the devices to the json config?

getting the following...
[2017-9-23 16:01:50] Loaded plugin: homebridge-smartthings
[2017-9-23 16:01:50] Registering platform 'homebridge-smartthings.SmartThings'
[2017-9-23 16:01:50] ---
[2017-9-23 16:01:50] Loaded config.json with 0 accessories and 1 platforms.
[2017-9-23 16:01:50] ---
[2017-9-23 16:01:50] Loading 1 platforms...
[2017-9-23 16:01:50] [SmartThings] Initializing SmartThings platform...
[2017-9-23 16:01:50] [SmartThings] Fetching Smart Things devices.
[2017-9-23 16:01:50] [SmartThings] Error received type undefined - undefined
[2017-9-23 16:01:50] [SmartThings] Unknown Capabilities: []

**Comment by kenlpeters** [comment]
Same Here. I have tried everything and this just continues to be the result. Has anyone figured it out?

**Comment by kenlpeters** [comment]
Any update on this issue?

**Comment by kenlpeters** [comment]
I have uninstalled and re-installed Homebridge and plugin and I still get the errors above.  I have tried everything except starting from scratch with a new install of Jessie, but I do not want to do that because I have other items running on my Pi.  So any help would be appreciated.

**Comment by steveternes** [comment]
I got it to work, it was the way i was listing the platforms & accessories. 

Thanks

Stephen Ternes

**Comment by jeffl78** [comment]
I'm hanging the same problem except my logs also report that it is "Loading 0 accessories".  This appears the line after it reports fetching SmartThings devices and before the errors you got.

**Comment by kenlpeters** [comment]
I finally figured it out. I delete the smart app from the SmartThings web portal. Then deleted it from Phone app. I then re-added it from github and enabled oauth. After that I published it. I then Went into my phone and add the smart app and clicked done. Then I went back into the smart app from the automation menu and clicked on the config. I copied the client id and secret id and put them in my config.json

**Comment by jeffl78** [comment]
I tired following these step and am getting the same error still.  Thanks for the advice anyway.

**Comment by 0xfgarcia** [comment]
Same error here...

Loading 1 platforms...
[2017-11-6 17:40:15] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[2017-11-6 17:40:15] [SmartThings] Fetching Smart Things devices.
[2017-11-6 17:40:15] Loading 0 accessories...
[2017-11-6 17:40:15] [SmartThings] Error received type undefined - undefined
[2017-11-6 17:40:15] [SmartThings] Unknown Capabilities: []
